#!/bin/bash

################################################################################
#
# Author: Paulo Costa (coostax@gmail.com)
# License: GNU/GPL, see http://www.gnu.org/copyleft/gpl.html
# Date: 2015-07-17
#
# FFMpeg compilation script
#
# Compiles FFMpeg from sources on git
#  Requires some libraries to compile
#  for ubuntu/debian do
# sudo apt-get -y --force-yes install autoconf automake build-essential libass-dev libfreetype6-dev \
#  libsdl1.2-dev libtheora-dev libtool libva-dev libvdpau-dev libvorbis-dev libxcb1-dev libxcb-shm0-dev \
#  libxcb-xfixes0-dev pkg-config texi2html zlib1g-dev yasm cmake mercurial curl
#
#
# usage:
#   install_ffmpeg [-i | -u] <install dir>
#       -i : installs from scratch (make sure to clean folders)
#       -u : updates the installation
#
# The install_dir argument is optional. If not set FFMpeg is installed in /opt/ffmpeg
################################################################################

#handle cmd line arguments
install_dir="/opt/ffmpeg"
install_type=0;

if [ -z $1 ]; then
	echo "installing on default path.."
else
	case "$1" in
		-i)
		install_type=0;
		if [ -z $2 ]; then
			install_dir = $2;
		fi
		;;
		-u)
		install_type=1;
		if [ -z $2 ]; then
			install_dir = $2;
		fi
		;;
		*)
		install_dir=$1;
		;;
	esac
fi

#create folders
ffmpeg_src=$install_dir/source
ffmpeg_build=$install_dir/build
ffmpeg_bin=$install_dir/bin

#TODO clean folders on update

#--create folders
mkdir -p $ffmpeg_src
mkdir -p $ffmpeg_build
mkdir -p $ffmpeg_bin
#set path for building
export PATH=$ffmpeg_bin:$PATH
#--H.264 video encoder
echo "preparing H.264 encoder"
cd $ffmpeg_src
git clone --depth 1 git://git.videolan.org/x264
cd x264
./configure --prefix="$ffmpeg_build" --bindir="$ffmpeg_bin" --enable-static
make
make install
make distclean
#--H.265/HEVC video encoder
echo "preparing H.265/HEVC video encoder"
cd $ffmpeg_src
hg clone https://bitbucket.org/multicoreware/x265
cd x265/build/linux
cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$ffmpeg_build" -DENABLE_SHARED:bool=off ../../source
make
make install
make distclean
#--libfdk-AAC audio encoder.
echo "preparing libfdk_AAC encoder"
cd $ffmpeg_src
git clone --depth 1 git://git.code.sf.net/p/opencore-amr/fdk-aac
cd fdk-aac
autoreconf -fiv
./configure --prefix="$ffmpeg_build" --disable-shared
make
make install
make distclean
#--MP3 audio encoder
echo "preparing MP3 encoder"
cd $ffmpeg_src
curl -L -O http://downloads.sourceforge.net/project/lame/lame/3.99/lame-3.99.5.tar.gz
tar xzvf lame-3.99.5.tar.gz
cd lame-3.99.5
./configure --prefix="$ffmpeg_build" --bindir="$ffmpeg_bin" --disable-shared --enable-nasm
make
make install
make distclean
#--OPUS audio decoder
echo "preparing OPUS audio decoder"
cd $ffmpeg_src
git clone git://git.opus-codec.org/opus.git
cd opus
autoreconf -fiv
./configure --prefix="$ffmpeg_build" --disable-shared
make
make install
make distclean
#--Ogg bitstream library
echo "preparing Ogg bitstream library"
cd $ffmpeg_src
curl -O http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.gz
tar xzvf libogg-1.3.2.tar.gz
cd libogg-1.3.2
./configure --prefix="$ffmpeg_build" --disable-shared
make
make install
make distclean
#--Vpx encoder
echo "preparing Libvpx video encoder"
cd $ffmpeg_src
git clone --depth 1 https://chromium.googlesource.com/webm/libvpx.git
cd libvpx
./configure --prefix="$ffmpeg_build" --disable-examples
make
make install
make clean
#--FFMPEG
echo "compiling FFMPEG"
cd $ffmpeg_src
git clone --depth 1 git://source.ffmpeg.org/ffmpeg
cd ffmpeg
PKG_CONFIG_PATH="$ffmpeg_build/lib/pkgconfig" ./configure --prefix="$ffmpeg_build" --extra-cflags="-I$ffmpeg_build/include" --extra-ldflags="-L$ffmpeg_build/lib" --bindir="$ffmpeg_bin" --enable-gpl --enable-nonfree --enable-libfdk_aac --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfreetype
make
make install
make distclean
hash -r
